name: GCP Infra & DBT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: europe-west1
      TF_VAR_cloud_run_image: ${{ vars.CLOUD_RUN_IMAGE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Autentication
      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2) Install gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3) Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # 4) Terraform init 
      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Terraform apply on (only push to main)
        if: github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve -input=false


  dbt:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Python & dbt-bigquery
        run: |
          python3 -m pip install --upgrade pip
          # Fijamos click a una versiÃ³n compatible y sobrescribimos la del sistema
          python3 -m pip install "click>=8.1.7,<9"
          python3 -m pip install "dbt-bigquery==1.8.0"

      - name: dbt build (only push main)
        if: github.event_name == 'push'
        working-directory: dbt_project
        run: dbt build

      - name: dbt build (pull request)
        if: github.event_name == 'pull_request'
        working-directory: dbt_project
        run: dbt build
