name: GCP Infra & DBT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: europe-west1
      TF_VAR_cloud_run_image: ${{ vars.CLOUD_RUN_IMAGE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Autentication
      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2) Install gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3) Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # 4) Terraform init 
      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Terraform apply on (only push to main)
        if: github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve -input=false


  dbt:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Python & dbt-bigquery
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install dbt-bigquery==1.8.0

      - name: dbt deps
        working-directory: dbt_project
        run: dbt deps

      - name: dbt run (solo en push a main)
        if: github.event_name == 'push'
        working-directory: dbt_project
        run: dbt run

      - name: dbt build (en PR, opcional)
        if: github.event_name == 'pull_request'
        working-directory: dbt_project
        run: dbt build --select state:modified+
